name: global_EBC
channels:
  - defaults
dependencies:
  - bleach
  - jedi
  - ipywidgets
  - xyzservices
  - python-dateutil
  - fonttools
  - pyogrio
  - importlib_resources
  - beautifulsoup4
  - pycparser
  - pandas
  - threadpoolctl
  - jupyter_console
  - numcodecs
  - folium
  - traitlets
  - geopandas
  - patsy
  - jupyterlab
  - fasteners
  - asciitree
  - packaging
  - pygments
  - nbformat
  - jsonschema
  - requests
  - send2trash
  - anyio
  - mapclassify
  - nest-asyncio
  - sniffio
  - branca
  - cycler
  - scikit-learn
  - netcdf4
  - debugpy
  - jupyterlab_widgets
  - httpx
  - jupyter_client
  - pyyaml
  - jupyter_core
  - typing_extensions
  - tornado
  - gdal
  - notebook
  - psutil
  - babel
  - arrow
  - defusedxml
  - click
  - scipy
  - cftime
  - seaborn
  - click-plugins
  - statsmodels
  - soupsieve
  - pyproj
  - shapely
  - numpy
  - networkx
  - urllib3
  - pyparsing
  - platformdirs
  - python=3.10
  - contourpy
  - zarr
  - matplotlib
  - jupyter_server
  - jupyter
  - cffi
  - certifi
  - wheel
  - zstandard
  - cached-property
  - nbclient
  - attrs
  - nbconvert-core
  - pysocks
  - terminado
  - charset-normalizer
  - fiona
  - pyzmq
  - joblib
  - setuptools
  - pip
  - ipython
  - brotli-python
  - pytz
  - pillow
  - jinja2
  - ipykernel
  - cligj
  - cartopy
  - xarray
  - pymannkendall
  - rioxarray
